name: Cherry-pick commit

on:
  workflow_dispatch:

jobs:
  cherry-pick:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch all branches
      run: git fetch --all

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Force checkout target branch
      run: git checkout -f FP-Staging

    - name: Cherry-pick commit
      run: |
        git cherry-pick 4c90f5b
        git push origin FP-Staging
