name: Cherry-pick commit to FP-Staging

on:
  workflow_dispatch:

jobs:
  cherry-pick:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch all branches
      run: git fetch --all

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Force checkout FP-Staging branch
      run: git checkout -f FP-Staging

    - name: Cherry-pick commit
      run: |
        git cherry-pick 2d6cf14b9a6d856bbd330b1056e8e25bfb9722ab
        git push origin FP-Staging
