name: Remove Specific Commit

on:
  workflow_dispatch:
    inputs:
      commit_id:
        description: 'Commit ID to remove'
        required: true
        type: string
      target_branch:
        description: 'Branch to remove commit from'
        required: true
        type: string
        default: 'main'

jobs:
  remove-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.target_branch }}

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Remove commit
        run: |
          if ! git rev-parse --verify ${{ github.event.inputs.commit_id }} >/dev/null 2>&1; then
            echo "Error: Commit ID does not exist"
            exit 1
          fi
          git rebase --rebase-merges --onto ${{ github.event.inputs.commit_id }}^ ${{ github.event.inputs.commit_id }}

      - name: Push changes
        run: |
          git push --force origin ${{ github.event.inputs.target_branch }}
