name: Steal Chubbs branch

on:
  workflow_dispatch:

permissions:
  contents: write  # Ensure the token has write permissions to delete branches

jobs:
  manage-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repo
        uses: actions/checkout@v3
        with:
          ref: FrogPilot  # Change this if your main branch name is different

      - name: Set up git config
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/Discountchubbs/FrogPilot.git
          git fetch upstream ChubbsPilot

      - name: Create new branch from upstream
        run: |
          git checkout -b FP-Staging-Chubbs upstream/FrogPilot-HKG

      - name: Push new branch
        run: |
          git push origin FP-Staging-Chubbs
